### ISSUE TITLE
ValueError with computing table

### ISSUE THREAD

**Issue by JacobCoblentz** [ustroetz/python-osrm#14]
Traceback (most recent call last):
  File "distmat.py", line 26, in <module>
    time_matrix , snapped_coords = osrm.table(latlon, output='dataframe', ids_origin=list_id, send_as_polyline=False)
  File "build/bdist.linux-x86_64/egg/osrm/core.py", line 335, in table
  File "/usr/lib64/python2.7/site-packages/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

What is going on with this? Running it on redhat 7

**Comment by mthh** [comment]
Hi!

This is probably a bit late but I guess your `list_id` object is not a `list` but either a `pandas.Series` or a `numpy.ndarray`.
This is why it fails like that when we are doing `if not ids_origin:` instead of doing something like `if ids_origin is not None:`.

**Comment by JacobCoblentz** [comment]
OH that makes sense- thank you
