### ISSUE TITLE
No requirements.txt file while trying to pip install 

### ISSUE THREAD

**Issue by nkochanek** [ustroetz/python-osrm#22]
I got the following error while trying to pip install osrm on ubuntu 16.04 

```
Collecting osrm
  Using cached https://files.pythonhosted.org/packages/b3/a9/210582e9023eb2bfa5146b4f7b3f900bdc4ed5bc57f09521fdd9b84504b4/osrm-0.11.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-UMJFUQ/osrm/setup.py", line 5, in <module>
        with open("requirements.txt") as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

Note* not a huge issue as it installs fine using ```setup.py install```

**Comment by mthh** [comment]
I guess the requirements.txt file is missing from the packaged release available from pypi ?
This requirements.txt file should probably be explicitly included when packaging a release by specifying it in a [MANIFEST.in file](https://docs.python.org/3.6/distutils/sourcedist.html#specifying-the-files-to-distribute).

**Comment by ustroetz** [comment]
Thanks for noticing @nkochanek and thanks for doing the research @mthh. I'll have a look. I have little experience publishing on pypi.

**Comment by ustroetz** [comment]
I pushed a new version (`osrm-0.11.3`) to PyPI include the MAINFEST.in file. Could you please give it another try an let me know if it works?

**Comment by mthh** [comment]
It installs perfectly from Pypi on my computer :+1:
