### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by alex6H** [ustroetz/python-osrm#30]
Hi,

I try to query
```
import osrm
result = osrm.simple_route([50.843920, 4.369253], [50.845794, 4.372178],output='route', overview="full", geometry='wkt')
result['geometry']
```
but the answer is an error `TypeError: list indices must be integers or slices, not str`

When i tried directly on OSRM server with
`http://127.0.0.1:5000/route/v1/driving/polyline(yjtYomiuHiQuJ)?overview=full&steps=false&alternatives=false&geometries=polyline&annotations=true&continue_straight=default`
I get a right answer.

What should i change ?

Thanks

```

**Comment by mthh** [comment]
The result of `simple_route` is a list (the error is telling you that you are trying to index that list with `geometry`).  
You should try `result[0]["geometry"]` ie the geometry of the first route.

**Comment by zifeo** [comment]
Please make sure the issue you report is about this library, not python related nor OSRM engine related.
