### ISSUE TITLE
Requirements.txt should have fixed version

### ISSUE THREAD

**Issue by zifeo** [ustroetz/python-osrm#32]
GDAL 3.0 seems to be an issue for some environment (e.g. docker python3.6-slim) and matplotlib had some changes : 
```
  File "/usr/local/lib/python3.6/site-packages/osrm/__init__.py", line 54, in <module>
    from .extra import AccessIsochrone
  File "/usr/local/lib/python3.6/site-packages/osrm/extra.py", line 14, in <module>
    from matplotlib.mlab import griddata
ImportError: cannot import name 'griddata'
```

**Comment by ozeranskiy** [comment]
Hi, I fixed the version of the library matplotlib and GDAL.
created pull request https://github.com/ustroetz/python-osrm/pull/33
while request not accept yet, I suggest using my fork

**Comment by ozeranskiy** [comment]
in the 3rd version of the matplotlib griddata function is removed and scipy.interpolate.griddata is recommended
