### ISSUE TITLE
ImportError: cannot import name 'griddata' 

### ISSUE THREAD

**Issue by janddd** [ustroetz/python-osrm#36]
I get the following error when importing this module.

```
  File "e:\software\anaconda3\envs\wmlpython3\lib\site-packages\osrm\extra.py", line 14, in <module>
    from matplotlib.mlab import griddata

ImportError: cannot import name 'griddata'
```

It seems that griddata from matplotlib.mlab is removed from the latest matplotlib versions.

See also link:

> https://matplotlib.org/3.1.0/api/api_changes.html
> 
> matplotlib.mlab removals
> Lots of code inside the matplotlib.mlab module which was deprecated in Matplotlib 2.2 has been removed. 
> 
> See below for a list:
> mlab.griddata (use scipy.interpolate.griddata)

**Comment by zifeo** [comment]
Thanks for reporting this issue.
It was fix by #33 but not published yet, you can install directly:
```shell
pip3 install git+ssh://git@github.com:ustroetz/python-osrm.git
```

**Comment by harisbal** [comment]
Hello, any chance to publish the fix.
It undermines an excellent library!

**Comment by Abhi8162** [comment]
im getting this error whil trying to import osrm. Any fix?
ImportError: cannot import name 'griddata' from 'matplotlib.mlab'

**Comment by MaximCamilleri** [comment]
hi, i am also still getting this error, any updates?

**Comment by Johnycrown** [comment]
I am getting this errors as well

**Comment by zhaomh1998** [comment]
I was able to temporarily resolve it by going into `extra.py` that caused the problem and replacing
`from matplotlib.mlab import griddata` with `from scipy.interpolate import griddata`.

**Comment by nepomnyi** [comment]
Thanks a lot man @zhaomh1998 ! 
Turns out `griddata` was removed from `matplotlib`.
A helpful example of how to convert your `matplotlib's griddata` to `scipy's griddata` is given in [the Olivier Gauthe's comment under this StackOverflow post](https://stackoverflow.com/a/14140554/10073233).
