### ISSUE TITLE
osrm import error

### ISSUE THREAD

**Issue by Chygos** [ustroetz/python-osrm#39]
I finally installed osrm but when I tried importing it into my notebook, an ImportError comes up.
It says:
ImportError: cannot import name 'griddata' from 'matplotlib.mlab'

From the matplotlib 3.1.1 version I am using the, mlab.griddata sub-module is not in existence.
Thanks.

**Comment by zifeo** [comment]
@Chygos Thanks for reporting, a new release should come soon. In the meanwhile, please use this solution: https://github.com/ustroetz/python-osrm/issues/36#issuecomment-530140507.
