### ISSUE TITLE
Onedrive error bad request 

### ISSUE THREAD

**Issue by Marlene98** [ustroetz/python-osrm#43]
Hi There,

i have multiple issues with one drive but I'm keen to get it going.
So first I'm using PDF Expert on my iPad and I linked OneDrive to it. When I tried to copy my files into the OneDrive folder it said bad request. Somehow it ended up copying some files, still my most important file for all my university stuff isn't copied to the folder and it keep on saying bad request. What can I do ? 
Also I connected OneDrive to my computer and moved the files into that folder but its not uploading. I read I had to do it one by one if its many files but its still not working.
Side info I have a business account if that's any helpful information. 

thank you in advance!

Marlene

**Comment by Marlene98** [comment]
okay forget about the second issue. Its working now. 
nevertheless I would be very grateful if someone could help me with the PDF expert issue.
Thanks

**Comment by neilfloow** [comment]
This does not appear to be related to `python-osrm` at all.
