### ISSUE TITLE
Features issue when geocoding

### ISSUE THREAD

**Issue by Thecoder352** [ustroetz/python-osrm#50]
I keep getting this error when trying to run this script: KeyError: 'features'

from mapbox import Geocoder
import pandas as pd
import json

geocoder = Geocoder(access_token=MAPBOX_ACCESS_TOKEN)

geocoder = Geocoder()

def load_dataset():
    """Load data from CSV."""
    citiDF = df
    return citiDF

def geocode_address(address):
    """Geocode street address into lat/long."""
    response = geocoder.forward(address)
    coords = str(response.json()['features'][0]['center'])
    coords = coords.replace(']', '')
    coords = coords.replace('[', '')
    return coords

def geocode_dataframe(row):
    """Geocode start and end address."""
    citiDF['Points'] = geocode_address(row['Location'])
    print(row)

citiDF = load_dataset()

**Comment by Thecoder352** [comment]
the csv and mapbox are in my variables with the pandas,pyodc, and numpy imports

**Comment by zifeo** [comment]
@Thecoder352 Do you use OSRM?
